Add `get_value_ptr`
MODFLOW-USGS/modflow6 pull request #1209
Opened 2023-04-24 11:59 UTC by Hofer-Julian

## Summary

By exposing `get_value_ptr_double` and `get_value_ptr_int` we are strictly speaking not BMI conform.
This PR fixes this aspect by adding `get_value_ptr`.
The corresponding PR on the xmipy side can be found here: https://github.com/Deltares/xmipy/pull/98
If merged, we should coordinate the next xmipy and MODFLOW 6 release

## Impact

- New versions of xmipy will not work with older versions of MODFLOW.
- The xmipy API stays the same.

## Alternative Approach
- Remove  `get_value_ptr_double` and `get_value_ptr_int` completely

2023-04-24 12:39 UTC, mjr-deltares commented
I think we will have to take this into consideration also in light of related, non-Fortran kernels having their BMI set up currently where we might want to use xmipy for those too. And if xmipy is extended with a connection to a native get_value_ptr function, we would want to have MODFLOW adapted. Not sure if we are instantly going to drop backward compat by removing the Fortran flavored get_value_ptr_double etc. Maybe deprecation is better here.

2023-05-08 14:28 UTC, jdhughes-usgs commented
@mjr-deltares should we merge and deal with the deprecation warning after this is in?

2023-05-15 10:56 UTC, mjr-deltares requested changes

2023-05-15 10:56 UTC, mjr-deltares commented on srcbmi/mf6bmi.f90
> +      write (bmi_last_error, fmt_unsupported_rank) trim(var_name)
This should be unsupported type, not rank

2023-05-15 10:59 UTC, mjr-deltares commented on srcbmi/mf6bmi.f90
> +      write (bmi_last_error, fmt_unsupported_rank) trim(var_name)
> @mjr-deltares should we merge and deal with the deprecation warning after this is in?

after fixing the error message above, we can do that. But I realized while looking at it again that we also have the get_value_* functions for each of the types, and then also the set_value_* counter parts. We should then probably treat those similarly.

2023-05-25 14:11 UTC, jdhughes-usgs approved these changes

2023-05-30 06:58 UTC, mjr-deltares approved these changes

2023-05-30 14:05 UTC, merged