feat(gwt-ist): add nonlinear sorption isotherms to immobile domain
MODFLOW-USGS/modflow6 pull request #2027
Opened 2024-10-01 12:33 UTC by langevin-usgs

Prior to this PR, the Immobile Storage and Transfer (IST) Package for the GWT Model supported only the LINEAR sorption isotherm.  This PR adds support for the nonlinear FREUNDLICH and LANGMUIR sorption isotherms, as discussed in #2018.  The SORPTION option in the IST Package requires specification of either LINEAR, FREUNDLICH, or LANGMUIR to follow the SORPTION keyword, which breaks backward compatibility for IST input files with only the SORPTION keyword specified.

The nonlinear sorption isotherms are expected to have a negative effect on convergence for the transport model as additional outer iterations will be required for an accurate solution.  Depending on the problem, it's possible that GWT models with nonlinear sorption in the immobile domain will have a hard time converging or may not converge at all.

Checklist of items for pull request

- [x] Replaced section above with description of pull request
- [ ] Referenced discussion #2018
- [ ] Added new test or modified an existing test
- [ ] Ran `ruff` on new and modified python scripts in .doc, autotests, doc, distribution, pymake, and utils subdirectories.
- [x] Formatted new and modified Fortran source files with `fprettify`
- [x] Added doxygen comments to new and modified procedures
- [ ] Updated meson files, makefiles, and Visual Studio project files for new source files
- [x] Updated [definition files](/MODFLOW-USGS/modflow6/tree/develop/doc/mf6io/mf6ivar)
- [ ] Updated [develop.tex](/MODFLOW-USGS/modflow6/doc/ReleaseNotes/develop.tex) with a plain-language description of the bug fix, change, feature; required for changes that may affect users
- [ ] Updated [input and output guide](/MODFLOW-USGS/modflow6/doc/mf6io)
- [ ] Removed checklist items not relevant to this pull request

For additional information see [instructions for contributing](/MODFLOW-USGS/modflow6/.github/CONTRIBUTING.md) and [instructions for developing](/MODFLOW-USGS/modflow6/.github/DEVELOPER.md).

2024-10-07 16:43 UTC, aprovost-usgs requested changes
A couple of things to discuss, I think.

2024-10-07 19:16 UTC, jdhughes-usgs commented on doc/ReleaseNotes/develop.tex
Seems it would be good to default to `LINEAR` if nothing is specified

2024-10-10 15:24 UTC, langevin-usgs commented on doc/ReleaseNotes/develop.tex
Agreed.  Defaults to LINEAR if not specified.

2024-10-10 15:26 UTC, langevin-usgs commented on doc/mf6io/mf6ivar/dfn/gwt-ist.dfn
good suggestion

2024-10-10 22:38 UTC, merged